### ISSUE TITLE
[Suggestion] Cloudflare Worker support python

### ISSUE THREAD

**Issue by p0we7** [lyc8503/apprise_vercel#1]
worker also supports python, so why not use it together?

**Comment by lyc8503** [comment]
I know that Cloudflare has introduced Python workers, and I know that additionally deploying apprise on vercel is not the best solution.

But as I mentioned in the uptimeflare wiki:

> However, the apprise library is written in Python, and Cloudflare's recently released python worker still has problems deploying apprise. So we are using Vercel serverless deployment for now and this part may change in the future. You can also use the [Apprise API](https://github.com/caronc/apprise-api) deployed by your own.

In fact, I've spent probably a couple hours trying to run apprise on Cloudflare Workers without success, and the wrangler is reporting errors that I can't understand at all.

The Cloudflare python worker uses Pyodide to run python in wasm, which is very different from the commonly used cpython and still seems to have quite a few compatibility issues to work out.

At the moment, it seems that using third-party libraries in Cloudflare Python Workers requires a lot of manual patching, and I can't do any patching at all with the current lack of clarity on error messages, whereas vercel provides a regular cpython environment, so I've gone with vercel for now.

I'll keep an eye on this section, and if Cloudflare Python Workers gets to a stable state in the future, I'll try it again.

**Comment by p0we7** [comment]
Thank you answer.
